version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./service-mqtt-broker/config:/mosquitto/config
      - ./service-mqtt-broker/auth:/etc/mosquitto/
      - ./service-mqtt-broker/certs:/mosquitto/certs
    expose:
      - "1883"
      - "8883"
      - "9001"
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"

  server-web-mqtt-client:
    image: httpd:2.4
    volumes:
      - ./web-mqtt-client:/usr/local/apache2/htdocs/
    ports:
      - "5001:80"

  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data
    depends_on:
      - mosquitto

  influxdb:
    image: influxdb:1.8
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: mydb
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password

  grafana:
    image: grafana/grafana:8.2.0
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  influxdb_data:
  grafana_data:

